entity ent_player();
entity ent_aitest();
entity ent_sword(unsigned char direction, uint16_t x, uint16_t y, unsigned char creator);
entity ent_axe(unsigned char direction, uint16_t x, uint16_t y, unsigned char creator);
entity ent_dialogue(unsigned char direction, uint16_t x, uint16_t y);
entity ent_wall(unsigned char tile);
entity ent_nonsolid(unsigned char x, unsigned char y, unsigned char tile);
entity ent_item(unsigned char type, unsigned char status);
entity ent_door(unsigned int tile, unsigned int destSx, unsigned int destSy, int destX, int destY);
entity ent_empty();